import os

novo = (
    '"""\n'
    'Script de renomeacao dos canais -- The Legendary Treasure Hunt Sundays\n'
    '\n'
    'Le os IDs dos canais do banco de dados e renomeia cada um no Discord\n'
    'para os nomes atuais (sem sufixo -th).\n'
    '\n'
    'Uso:\n'
    '    python scripts/setup_treasure_hunt_once.py\n'
    '"""\n'
    '\n'
    'import asyncio\n'
    'import json\n'
    'import os\n'
    'import sys\n'
    '\n'
    'sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n'
    '\n'
    'import discord\n'
    'from dotenv import load_dotenv\n'
    '\n'
    'load_dotenv()\n'
    '\n'
    'BANCO_FILE = ".bancos/treasure_hunt.json"\n'
    '\n'
    '# Mapeamento: chave do banco -> (novo_nome, novo_topic)\n'
    'NOMES = {\n'
    '    "banco":    ("\U0001f4c5\ufe31evento-atual", "Painel do evento ativo \u2014 mapa, semana e estat\u00edsticas."),\n'
    '    "cadastro": ("\U0001f4cb\ufe31cadastro",     "Cadastre-se no Treasure Hunt aqui."),\n'
    '    "ranking":  ("\U0001f3c6\ufe31ranking",      "Ranking atualizado do evento."),\n'
    '    "provas":   ("\U0001f4f8\ufe31provas",       "Envie suas provas aqui."),\n'
    '    "logs":     ("\U0001f512\ufe31logs",         "Logs admin \u2014 Treasure Hunt."),\n'
    '}\n'
    '\n'
    '\n'
    'class RenameClient(discord.Client):\n'
    '    def __init__(self):\n'
    '        intents = discord.Intents.default()\n'
    '        intents.guilds = True\n'
    '        super().__init__(intents=intents)\n'
    '\n'
    '    async def on_ready(self):\n'
    '        print(f"[RENAME] Logado como {self.user}")\n'
    '        try:\n'
    '            await self.renomear_canais()\n'
    '        except Exception as e:\n'
    '            print(f"[RENAME] Erro: {e}")\n'
    '            import traceback\n'
    '            traceback.print_exc()\n'
    '        finally:\n'
    '            await self.close()\n'
    '\n'
    '    async def renomear_canais(self):\n'
    '        if not os.path.exists(BANCO_FILE):\n'
    '            print(f"[RENAME] Banco nao encontrado: {BANCO_FILE}")\n'
    '            return\n'
    '\n'
    '        with open(BANCO_FILE, "r", encoding="utf-8") as f:\n'
    '            banco = json.load(f)\n'
    '\n'
    '        channels = banco.get("channels", {})\n'
    '\n'
    '        for chave, (nome, topic) in NOMES.items():\n'
    '            canal_id = channels.get(chave)\n'
    '            if not canal_id:\n'
    '                print(f"[RENAME] {chave!r} sem ID no banco -- pulando.")\n'
    '                continue\n'
    '\n'
    '            canal = self.get_channel(canal_id)\n'
    '            if not isinstance(canal, discord.TextChannel):\n'
    '                print(f"[RENAME] Canal {canal_id} ({chave}) nao encontrado -- pulando.")\n'
    '                continue\n'
    '\n'
    '            nome_atual = canal.name\n'
    '            await canal.edit(name=nome, topic=topic)\n'
    '            print(f"[RENAME] #{nome_atual} -> #{nome}")\n'
    '\n'
    '\n'
    'def main():\n'
    '    token = os.getenv("DISCORD_TOKEN")\n'
    '    if not token:\n'
    '        print("[RENAME] DISCORD_TOKEN nao encontrado no .env")\n'
    '        sys.exit(1)\n'
    '\n'
    '    client = RenameClient()\n'
    '    asyncio.run(client.start(token))\n'
    '\n'
    '\n'
    'if __name__ == "__main__":\n'
    '    main()\n'
)

with open(r"c:\Users\Ciano\Documents\oBobonicClean\scripts\setup_treasure_hunt_once.py", "w", encoding="utf-8") as f:
    f.write(novo)

print("OK")
